spring.application.name=smartblock


spring.datasource.url= jdbc:postgresql://localhost:5432/smart_block
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
